# Site settings
title: Tanner Lancaster
header-img: img/sogo.jpg
email: tannerlancaster@gmail.com
copyright_name: saltillokid11
description: > # this means to ignore newlines until "baseurl:"
  Please wipe your feet before entering.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  saltillokid11
learn_profile: saltillokid11
email_username: tannerlancaster@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]

theme: jekyll-theme-hacker