# Site settings
title: This is the story that never ends!
header-img: img/home-bg.png
email: tanner@flatironschool.com
copyright_name: saltillokid11
description: > # this means to ignore newlines until "baseurl:"
  subtitle that never ends
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  saltillokid11
learn_profile: saltillokid11
email_username: tanner@flatironschool.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
